quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.live-reload.instrumentation=true
api.key=${API_KEY:dev-api-key-for-testing}
quarkus.swagger-ui.enabled=true
quarkus.swagger-ui.always-include=true
# %dev.quarkus.smallrye-openapi.store-schema-directory=openapi-spec-store
