apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esuite-data-extractie.fullname" . }}
  labels:
    {{- include "esuite-data-extractie.labels" . | nindent 4 }}
stringData:
  QUARKUS_DATASOURCE_PASSWORD: "{{ required "Valid .Values.db.password entry required!" .Values.db.password | toString }}"
  API_KEY_VALUE: "{{ required "Valid .Values.apiKey entry required!" .Values.apiKey | toString }}"
