###
GET {{base-url}}/referentietabellen
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.results.length === 100, "Response body results size is not 100")
        client.assert(response.body.count === 135, "Response body count is not 135")
        client.assert(!response.body.previousPage, "Response body previousPage is not false")
        client.assert(response.body.nextPage, "Response body nextPage is not true")
    });
%}

###
GET {{base-url}}/referentietabellen/Test_Exporteren_Alle_Verschillende_datatypen
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.aantalRecords === 1323, "Response body aantalRecords is not 1323")
    });
%}

###
GET {{base-url}}/referentietabellen/Test_Exporteren_Alle_Verschillende_datatypen/records
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.results.length === 100, "Response body results size is not 100")
        client.assert(response.body.count === 1323, "Response body count is not 1323")
        client.assert(!response.body.previousPage, "Response body previousPage is not false")
        client.assert(response.body.nextPage, "Response body nextPage is not true")
    });
%}
