apiVersion: v2
name: esuite-data-extractie
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: common
    version: "2.x.x"
    repository: "https://charts.bitnami.com/bitnami"
