### Bedrijven met KvK nummer.
GET {{base-url}}/bedrijven?kvk_nummer=11111111
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.results.length === 15, "Response body results size is not 15")
        client.assert(response.body.count === 15, "Response body count is not 15")
        client.assert(!response.body.previousPage, "Response body previousPage is not false")
        client.assert(!response.body.nextPage, "Response body nextPage is not false")
    });
%}

### Bedrijven met vestigingsnummer.
GET {{base-url}}/bedrijven?vestigingsnummer=777761616112
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.results.length === 1, "Response body results size is not 1")
        client.assert(response.body.count === 1, "Response body count is not 1")
        client.assert(!response.body.previousPage, "Response body previousPage is not false")
        client.assert(!response.body.nextPage, "Response body nextPage is not false")
    });
%}

### Bedrijf met KvK nummer en vestigingsnummer.
GET {{base-url}}/bedrijven?kvk_nummer=11111111&vestigingsnummer=777761616112
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.results.length === 1, "Response body results size is not 1")
        client.assert(response.body.count === 1, "Response body count is not 1")
        client.assert(!response.body.previousPage, "Response body previousPage is not false")
        client.assert(!response.body.nextPage, "Response body nextPage is not false")
    });
%}

### Bedrijf met KvK nummer en vestigingsnummer bestaat niet
GET {{base-url}}/bedrijven?kvk_nummer=11111111&vestigingsnummer=777761616343
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.results.length === 0, "Response body results size is not 0")
        client.assert(response.body.count === 0, "Response body count is not 0")
        client.assert(!response.body.previousPage, "Response body previousPage is not false")
        client.assert(!response.body.nextPage, "Response body nextPage is not false")
    });
%}

### Bedrijven zonder KvK nummer en vestigingsnummer
GET {{base-url}}/bedrijven
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.melding === "Either KvK nummer or vestigingsnummer must be provided", "Response body melding is not \"Either KvK nummer or vestigingsnummer must be provided\"")
    });
%}

### Bedrijf met invalide KvK nummer en vestigingsnummer.
GET {{base-url}}/bedrijven?kvk_nummer=11111111x&vestigingsnummer=777761616112x
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.melding === "Validatie fout(en)", "Response body melding is not \"Validatie fout(en)\"")
        client.assert(response.body.fouten.length === 2, "Response body fouten size is not 2")
    });
%}

### Bedrijf op identifier
GET {{base-url}}/bedrijven/854559
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Niet bestaand bedrijf op identifier
GET {{base-url}}/bedrijven/854559928347
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 404");
        client.assert(response.body.melding === "Bedrijf with identifier '854559928347' not found", "Response body melding is not \"Bedrijf with identifier '854559928347' not found\"")
    });
%}
