### Persoon met bsn.
GET {{base-url}}/personen?bsn=220290258
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.burgerServiceNummer === "220290258", "Response body burgerServiceNummer is not \"220290258\"")
    });
%}

### Persoon met bsn welke niet wordt gevonden
GET {{base-url}}/personen?bsn=644166800
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### Persoon met ongeldig bsn.
GET {{base-url}}/personen?bsn=987654321
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.melding === "Validatie fout(en)", "Response body melding is not \"Validatie fout(en)\"")
        client.assert(response.body.fouten.length === 1, "Response body fouten size is not 1")
    });
%}

### Persoon met ongeldig bsn.
GET {{base-url}}/personen?bsn=220290258xx
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.melding === "Validatie fout(en)", "Response body melding is not \"Validatie fout(en)\"")
        client.assert(response.body.fouten.length === 1, "Response body fouten size is not 1")
    });
%}

### Persoon met zonder bsn.
GET {{base-url}}/personen
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.melding === "Validatie fout(en)", "Response body melding is not \"Validatie fout(en)\"")
        client.assert(response.body.fouten.length === 1, "Response body fouten size is not 1")
    });
%}

### Persoon op identifier
GET {{base-url}}/personen/4115
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.burgerServiceNummer === "220290258", "Response body burgerServiceNummer is not \"220290258\"")
    });
%}

### Persoon met ongeldige identifier
GET {{base-url}}/personen/xxx
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.fouten[0].message === "Invalide niet negatieve integer", "Response body.fouten[0].message is not \"Invalide niet negatieve integer\"")
    });
%}
