### Persoon met bsn.
GET {{base-url}}/personen?bsn=220290258
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Persoon met ongeldig bsn.
GET {{base-url}}/personen?bsn=220290258xx
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Persoon met zonder bsn.
GET {{base-url}}/personen
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Persoon op identifier
GET {{base-url}}/personen/4115
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
