###
GET {{base-url}}/zaken?zaaktype=MigratieTest1
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&inclusiefOpen=true
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&inclusiefOpen=false
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&inclusiefOpen=xxx
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&page=1
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&page=2
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&page=99
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&page=x&page_size=y
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

###
GET {{base-url}}/zaken?zaaktype=MigratieTest1&page=-1&page_size=-1
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Zaak met besluit.
GET {{base-url}}/zaken/12-2023
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Zaak met documenten
GET {{base-url}}/zaken/182-2025
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Zaak met documenten, contacten, bagobjecten en gerelateerde zaken.
GET {{base-url}}/zaken/2011-2019
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Zaak met archiveerGegevens.overgebrachteGegevens
GET {{base-url}}/zaken/3783-2016
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Zaak met archiveerGegevens
GET {{base-url}}/zaken/116-2025
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Zaak met persoon met bsn als initiator en 2 personen en bedrijf als betrokkenen waarvan persoon notitie heeft
GET {{base-url}}/zaken/337-2023
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Zaak met bedrijf als initiator
GET {{base-url}}/zaken/1718-2020
X-API-KEY: {{api-key}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### GCP2
GET {{base-url}}/zaken/180-2025
X-API-KEY: {{api-key}}

