GET localhost:8080/zaken?zaaktype=MigratieTest1
X-API-KEY: dev-api-key-for-testing

###
GET localhost:8080/zaken?zaaktype=MigratieTest1&page=1
X-API-KEY: dev-api-key-for-testing

###
GET localhost:8080/zaken?zaaktype=MigratieTest1&page=2
X-API-KEY: dev-api-key-for-testing

### Zaak met besluit.
GET localhost:8080/zaken/12-2023
X-API-KEY: dev-api-key-for-testing

### Zaak met documenten
GET localhost:8080/zaken/182-2025
X-API-KEY: dev-api-key-for-testing

### Zaak met documenten, contacten, bagobjecten en gerelateerde zaken.
GET localhost:8080/zaken/2011-2019
X-API-KEY: dev-api-key-for-testing

### Zaak met archiveerGegevens.overgebrachteGegevens
GET localhost:8080/zaken/3783-2016
X-API-KEY: dev-api-key-for-testing

### Zaak met archiveerGegevens
GET localhost:8080/zaken/116-2025
X-API-KEY: dev-api-key-for-testing

### Zaak met persoon met bsn als initiator en 2 personen en bedrijf als betrokkenen waarvan persoon notitie heeft
GET localhost:8080/zaken/337-2023
X-API-KEY: dev-api-key-for-testing

### Zaak met bedrijf als initiator
GET localhost:8080/zaken/1718-2020
X-API-KEY: dev-api-key-for-testing
