GET localhost:8080/zaken?zaaktype=MigratieTest1

###
GET localhost:8080/zaken?zaaktype=MigratieTest1&page=1

###
GET localhost:8080/zaken?zaaktype=MigratieTest1&page=2

### Zaak met besluit.
GET localhost:8080/zaken/12-2023

### Zaak met documenten
GET localhost:8080/zaken/182-2025

### Zaak met documenten, contacten, bagobjecten en gerelateerde zaken.
GET localhost:8080/zaken/2011-2019

### Zaak met archiveerGegevens.overgebrachteGegevens
GET localhost:8080/zaken/3783-2016

### Zaak met archiveerGegevens
GET localhost:8080/zaken/116-2025

### Zaak met persoon met bsn als initiator en 2 personen en bedrijf als betrokkenen waarvan persoon notitie heeft
GET localhost:8080/zaken/337-2023

### Zaak met bedrijf als initiator
GET localhost:8080/zaken/1718-2020

